version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: bugtracker_db
    restart: always
    environment:
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: